# TCL File Generated by Component Editor 18.1
# Fri Apr 03 16:46:23 BST 2020
# DO NOT MODIFY


# 
# ci_cos "ci_cos" v1.0
#  2020.04.03.16:46:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ci_cos
# 
set_module_property DESCRIPTION ""
set_module_property NAME ci_cos
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ci_cos
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cordic
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cordic.v VERILOG PATH ip/cordic/cordic.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point ncs_cis0
# 
add_interface ncs_cis0 nios_custom_instruction end
set_interface_property ncs_cis0 clockCycle 35
set_interface_property ncs_cis0 operands 2
set_interface_property ncs_cis0 ENABLED true
set_interface_property ncs_cis0 EXPORT_OF ""
set_interface_property ncs_cis0 PORT_NAME_MAP ""
set_interface_property ncs_cis0 CMSIS_SVD_VARIABLES ""
set_interface_property ncs_cis0 SVD_ADDRESS_GROUP ""

add_interface_port ncs_cis0 theta dataa Input 32
add_interface_port ncs_cis0 n datab Input 32
add_interface_port ncs_cis0 result result Output 32
add_interface_port ncs_cis0 clk clk Input 1
add_interface_port ncs_cis0 reset reset Input 1

